### ISSUE TITLE
API Key provided is not valid

### ISSUE THREAD

**Issue by Me-sudoer** [make-all/metlink-nz#1]
Hi there,

Thank you for writing this integration. I have the below issue after pasting in my valid API key using the UI integration.
Error: "The api key provided is not valid."

When I configure the integration in my sensor.yaml; results are unavailable (I configure my sensors in a sperate file).

Sensor.yaml
- platform: metlink
  api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  stops:
  - stop_id: 3244
    route: CP
  - stop_id: 5008
    destination: 3244
    num_departures: 3

**Comment by make-all** [comment]
Metlink has this strange setup where in addition to signing up for a developer key, you need to subscribe to the API you want (strange, since they only offer one API).

If you go to https://opendata.metlink.org.nz/apis do you have the option to "Subscribe" there?

**Comment by Me-sudoer** [comment]
Hey there,

I have logged and there are no API's published and no option to subscribe.
However, I do have the option to "Get" various gtfs datasets.. Are there
particular datasets that I should choose to get?

Thanks,

**Comment by Me-sudoer** [comment]
Hi again,

I browsed the site again, following the links on the site rather than the
direct URL; doing it this way gave me the option to subscribe.

Everything is working now. Thanks!

**Comment by make-all** [comment]
Thanks. I've added a hint to that error message, as I think a lot of people will miss this.
