### ISSUE TITLE
Listing Multiple Departures in Dashboard

### ISSUE THREAD

**Issue by stevewrightnz** [make-all/metlink-nz#5]
Hi Jason

Nice Integration!

Quick question.  If "Number of Departures to Track" is set to 3 then is it possible to show the next 3 departures on a card?  If so which one would you use?

SteveW

**Comment by stevewrightnz** [comment]
Sorted - I found the answer in the Wiki :)

**Comment by make-all** [comment]
There is an example here that might help: https://github.com/make-all/metlink-nz/wiki

I use an entities card to list all the departures.  The example uses two lines per departure, one with the name of the service and one with the time it is due, but it is also possible to combine these into a single line using the template-entity-row custom component.
