### ISSUE TITLE
Error Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by droopanu** [make-all/metlink-nz#7]
I get this error when trying to reconfigure the integration:

Error
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

Cheers,
Liviu

**Comment by make-all** [comment]
Thanks, this seems to be an API change that wasn't highlighted when they recommended async_get as a replacement for async_get_registry which got removed in 2023.5, and recently turned into an error due to an optimisation in HA 2023.6.
