### ISSUE TITLE
Question: would it be possible to add "vehicle_id" and "monitored" as attributes?

### ISSUE THREAD

**Issue by droopanu** [make-all/metlink-nz#8]

**Comment by make-all** [comment]
That looks straightforward.  In the meantime, I think monitored can be figured out from the status, as if it is not monitored it should always show "scheduled" (or "sched", I don't remember if the abbreviation is from the data, or just for the signs) if I am understanding the meaning of that attribute correctly.
[Edit: I just checked some test calls, and the status (and vehicle_id) is coming through as null when monitored is false.]
